"""empty message

Revision ID: 30a93867cb68
Revises: 7ae73e20bad6
Create Date: 2026-03-17 13:46:10.801715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '30a93867cb68'
down_revision = '7ae73e20bad6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_bill_items', schema=None) as batch_op:
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=True)
        batch_op.drop_constraint(batch_op.f('service_bill_items_ibfk_1'), type_='foreignkey')
        batch_op.drop_constraint(batch_op.f('service_bill_items_ibfk_2'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'services', ['service_id'], ['id'], ondelete='SET NULL')
        batch_op.create_foreign_key(None, 'bills', ['bill_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('service_bill_items', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('service_bill_items_ibfk_2'), 'services', ['service_id'], ['id'])
        batch_op.create_foreign_key(batch_op.f('service_bill_items_ibfk_1'), 'bills', ['bill_id'], ['id'])
        batch_op.alter_column('service_id',
               existing_type=mysql.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
