"""empty message

Revision ID: bc8ebeded62f
Revises: 5e7bd7b2c195
Create Date: 2026-02-26 20:11:44.859419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bc8ebeded62f'
down_revision = '5e7bd7b2c195'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('item_status', sa.String(length=20), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.drop_column('item_status')

    # ### end Alembic commands ###
