"""empty message

Revision ID: c4dd46e4ddac
Revises: 64a6dc3bfd04
Create Date: 2026-03-06 20:13:36.311287

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c4dd46e4ddac'
down_revision = '64a6dc3bfd04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('customer_type', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.drop_column('customer_type')

    # ### end Alembic commands ###
