"""empty message

Revision ID: d2ffc469be6f
Revises: 906af96039a3
Create Date: 2026-02-26 12:02:42.609210

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd2ffc469be6f'
down_revision = '906af96039a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.alter_column('product_type',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               existing_nullable=True)
        batch_op.drop_column('created_at')

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', sa.Integer(), nullable=True))
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=False)
        batch_op.drop_column('payment_details')
        batch_op.drop_column('discount_amount')
        batch_op.drop_column('due_amount')
        batch_op.drop_column('tax_amount')

    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.alter_column('payment_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=100),
               nullable=True)
        batch_op.drop_column('card_number')
        batch_op.drop_column('cash_received')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('upi_id')
        batch_op.drop_column('card_holder_name')
        batch_op.drop_column('transaction_id')
        batch_op.drop_column('cheque_number')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cheque_number', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('transaction_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('card_holder_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('upi_id', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('bank_name', mysql.VARCHAR(length=100), nullable=True))
        batch_op.add_column(sa.Column('cash_received', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('card_number', mysql.VARCHAR(length=20), nullable=True))
        batch_op.alter_column('payment_id',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               nullable=False)

    with op.batch_alter_table('bills', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tax_amount', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('due_amount', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('discount_amount', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('payment_details', mysql.JSON(), nullable=True))
        batch_op.alter_column('customer_name',
               existing_type=mysql.VARCHAR(length=100),
               nullable=True)
        batch_op.drop_column('created_by')

    with op.batch_alter_table('bill_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', mysql.DATETIME(), nullable=True))
        batch_op.alter_column('product_type',
               existing_type=sa.String(length=100),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
